export const Environments = {
  TABLE_NAME_EVENT_TYPE: process.env.TABLE_NAME_EVENT_TYPE as string,
  TABLE_NAME_RESOURCES: process.env.TABLE_NAME_RESOURCES as string,
  TABLE_NAME_ERRORS: process.env.TABLE_NAME_ERRORS as string,
  TABLE_NAME_HISTORY: process.env.TABLE_NAME_HISTORY as string,
  TABLE_NAME_UNPROCESSED: process.env.TABLE_NAME_UNPROCESSED as string,
  SNS_TOPIC_ARN: process.env.SNS_TOPIC_ARN as string,
};

export const ALLOW_SERVICES = [
  'acm.amazonaws.com',
  'apigateway.amazonaws.com',
  'appmesh.amazonaws.com',
  'autoscaling.amazonaws.com',
  'backup.amazonaws.com',
  'cloudformation.amazonaws.com',
  'cloudbuild.amazonaws.com',
  'cloudcommit.amazonaws.com',
  'clouddeploy.amazonaws.com',
  'cloudpipeline.amazonaws.com',
  'cognito-identity.amazonaws.com',
  'cognito-idp.amazonaws.com',
  'connect.amazonaws.com',
  'dynamodb.amazonaws.com',
  'ebs.amazonaws.com',
  'ec2.amazonaws.com',
  'ecr.amazonaws.com',
  'ecs.amazonaws.com',
  'elasticloadbalancing.amazonaws.com',
  'elasticfilesystem.amazonaws.com',
  'firehose.amazonaws.com',
  'fsx.amazonaws.com',
  'glacier.amazonaws.com',
  'iam.amazonaws.com',
  'kinesis.amazonaws.com',
  'kms.amazonaws.com',
  'lambda.amazonaws.com',
  'logs.amazonaws.com',
  'rds.amazonaws.com',
  'route53.amazonaws.com',
  'route53domains.amazonaws.com',
  'route53resolver.amazonaws.com',
  'secretsmanager.amazonaws.com',
  'serverlessrepo.amazonaws.com',
  'servicediscovery.amazonaws.com',
  'sns.amazonaws.com',
  'sqs.amazonaws.com',
  'ssm.amazonaws.com',
  'sts.amazonaws.com',
  'waf-regional.amazonaws.com',
  'waf.amazonaws.com',
  'wafv2.amazonaws.com',
  'xray.amazonaws.com',
  'guardduty.amazonaws.com',
  'inspector.amazonaws.com',
  'securityhub.amazonaws.com',
];
