import { Paths, SVG } from '@constants';
import { SERVICES } from './Consts';

const MENUS = [
  {
    eventSource: SERVICES.EC2,
    category: 'compute',
    title: 'Amazon EC2',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.EC2],
    icon: SVG.EC2Icon,
  },
  {
    eventSource: SERVICES.LAMBDA,
    category: 'compute',
    title: 'AWS LAMBDA',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.LAMBDA],
    icon: SVG.LambdaIcon,
  },
  {
    eventSource: SERVICES.RDS,
    category: 'database',
    title: 'Amazon RDS',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.RDS],
    icon: SVG.RDSIcon,
  },
  {
    eventSource: SERVICES.DYNAMODB,
    category: 'database',
    title: 'Amazon DYNAMODB',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.DYNAMODB],
    icon: SVG.DynamoDBIcon,
  },
  {
    eventSource: SERVICES.S3,
    category: 'storage',
    title: 'Amazon S3',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.S3],
    icon: SVG.S3Icon,
  },
  {
    eventSource: SERVICES.EFS,
    category: 'storage',
    title: 'Amazon EFS',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.EFS],
    icon: SVG.EFSIcon,
  },
  {
    eventSource: SERVICES.CLOUDFRONT,
    category: 'networking',
    title: 'Amazon CloudFront',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.CLOUDFRONT],
    icon: SVG.CloudFrontIcon,
  },
  {
    eventSource: SERVICES.ROUTE53,
    category: 'networking',
    title: 'Amazon Route53',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.ROUTE53],
    icon: SVG.Route53Icon,
  },
  {
    eventSource: SERVICES.ELB,
    category: 'networking',
    title: 'Amazon ELB',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.ELB],
    icon: SVG.ELBIcon,
  },
  {
    eventSource: SERVICES.APPMESH,
    category: 'networking',
    title: 'AWS AppMesh',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.APPMESH],
    icon: SVG.AppMeshIcon,
  },
  {
    eventSource: SERVICES.IAM,
    category: 'security',
    title: 'AWS IAM',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.IAM],
    icon: SVG.IAMIcon,
  },
  {
    eventSource: SERVICES.DS,
    category: 'security',
    title: 'AWS DIRECTORY SERVICE',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.DS],
    icon: SVG.DSIcon,
  },
  {
    eventSource: SERVICES.SNS,
    category: 'application',
    title: 'Amazon SNS',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.SNS],
    icon: SVG.SNSIcon,
  },
  {
    eventSource: SERVICES.SQS,
    category: 'application',
    title: 'Amazon SQS',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.SQS],
    icon: SVG.SQSIcon,
  },
  {
    eventSource: SERVICES.STEP_FUNCTION,
    category: 'application',
    title: 'AWS Step Functions',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.STEP_FUNCTION],
    icon: SVG.StepFunctionIcon,
  },
  {
    eventSource: SERVICES.CONNECT,
    category: 'application',
    title: 'Amazon Connect',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.CONNECT],
    icon: SVG.ConnectIcon,
  },
  {
    eventSource: SERVICES.ES,
    category: 'analytics',
    title: 'Amazon ElasticSearch',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.ES],
    icon: SVG.ESIcon,
  },
  {
    eventSource: SERVICES.REDSHIFT,
    category: 'analytics',
    title: 'Amazon Redshift',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.REDSHIFT],
    icon: SVG.RedshiftIcon,
  },
  {
    eventSource: SERVICES.KINESIS,
    category: 'analytics',
    title: 'Amazon Kinesis',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.KINESIS],
    icon: SVG.KinesisIcon,
  },
  {
    eventSource: SERVICES.FIREHOSE,
    category: 'analytics',
    title: 'Amazon Data Firehose',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.FIREHOSE],
    icon: SVG.FirehoseIcon,
  },
  {
    eventSource: SERVICES.EKS,
    category: 'container',
    title: 'Amazon EKS',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.EKS],
    icon: SVG.EKSIcon,
  },
  {
    eventSource: SERVICES.LEX,
    category: 'machine learning',
    title: 'Amazon Lex',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.LEX],
    icon: SVG.LexIcon,
  },
  {
    eventSource: SERVICES.CODEBUILD,
    category: 'devops',
    title: 'AWS CodeBuild',
    path: Paths.ROUTE_PATHS[Paths.ROUTE_PATH_INDEX.CODEBUILD],
    icon: SVG.CodeBuildIcon,
  },
];

export default MENUS;
