GET http://localhost:8080/auth/health


POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "6q>xJCAl3%",
  "newPassword": "Session10+"
}

POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "Session10+"
}