name: PUSH_B) Backend Build

on:
  push:
    paths:
      - backend/daily_batch/**
      - backend/cloudtrail/**
      - .github/workflows/push_backend.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

jobs:
  Lambda_DailyBatch:
    concurrency: dailybatch
    uses: ./.github/workflows/reusable_lambda_code.yml
    with:
      region: us-east-1
      working-directory: backend/daily_batch
      function-name: spotlight-dailybatch-dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Lambda_CloudTrail:
    concurrency: cloudtrail
    uses: ./.github/workflows/reusable_lambda_container.yml
    with:
      region: us-east-1
      working-directory: backend/cloudtrail
      function-name: spotlight-cloudtrail-process-dev
      dockerfile: Dockerfile.CloudTrail
      repository: spotlight/cloudtrail-dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
