name: PUSH_B) Release Events

on:
  push:
    paths:
      - backend/src/release_events/**
      - .github/workflows/push_release_events.yml
    branches-ignore:
      - releases/**
  workflow_run:
    workflows:
      - PUSH_B) Auth Manager Build
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: backend/src/release_events

jobs:
  build:
    runs-on: ubuntu-18.04
    environment:
      name: dev
    env:
      TABLE_NAME_SETTINGS: ${{ secrets.TABLE_NAME_SETTINGS }}
      TABLE_NAME_EVENT_TYPE: ${{ secrets.TABLE_NAME_EVENT_TYPE }}
      TABLE_NAME_HISTORY: ${{ secrets.TABLE_NAME_HISTORY }}
      TABLE_NAME_RESOURCE: ${{ secrets.TABLE_NAME_RESOURCE }}
      BUCKET_ARCHIVE: ${{ secrets.BUCKET_ARCHIVE }}
      SQS_URL: ${{ secrets.SQS_URL }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # Installation
      - name: Build
        run: |
          yarn install

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # AWS Credentials
      - name: Release Notes
        run: |
          yarn releases
          yarn events
