name: PUSH_T) Service Build

on:
  push:
    branches:
      - master
    paths:
      - terraform/services/**
      - .github/workflows/push_terraform_services.yml
    branches-ignore:
      - releases/**
  workflow_run:
    workflows:
      - PUSH_T) Setup Build
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

env:
  TF_WORKSPACE: dev
  TF_VAR_region: ap-northeast-1
  TF_VAR_admin_email: ${{ secrets.ADMIN_EMAIL }} 
  AWS_DEFAULT_REGION: ap-northeast-1
  WORKING_DIR: terraform/services

jobs:
  Update:
    runs-on: ubuntu-18.04
    environment:
      name: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # Install the latest version of Terraform CLI 
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      # Terraform Apply
      - name: Terraform Apply
        run: |
          terraform init
          terraform plan -out=services
          terraform apply "services"
