name: PUSH_T) Backend Build

on:
  push:
    paths:
      - backend/terraform/**
      - .github/workflows/push_terraform_backend.yml
    branches-ignore:
      - releases/**
  workflow_run:
    workflows:
      - PUSH_T) Service Build
    branches:
      - master
    types:
      - completed

env:
  TF_VAR_region: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: backend/terraform

jobs:
  build:
    runs-on: ubuntu-18.04
    environment:
      name: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install the latest version of Terraform CLI 
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      # Setup init
      - name: Terraform Init
        run: terraform init

      # Setup plan
      - name: Terraform Plan
        run: terraform plan -out=backend

      # Setup apply
      - name: Terraform Apply
        run: terraform apply "backend"
