name: PUSH_B) Lambda Building

on:
  push:
    paths:
      - backend/src/daily_query/**
      - .github/workflows/push_backend_lambda.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

jobs:
  DailyQuery:
    uses: ./.github/workflows/reuse_lambda.yml
    with:
      region: us-east-1
      working-directory: backend/src/daily_query
      environment: dev
      outputs-bucket: spotlight-material
      function-name: daily_query
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
