name: PUSH_T) Terraform Build

on:
  push:
    paths:
      - terraform/**
      - .github/workflows/push_terraform.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: terraform
  Environment: dev

jobs:
  Update:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Terraform Apply
      - name: Terraform Apply
        run: |
          terraform init
          terraform workspace select ${{ env.Environment }}
          terraform plan -out=setup
          terraform apply "setup"
