name: PUSH_F) React Build

on:
  push:
    paths:
      - frontend/**
      - .github/workflows/push_frontend.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: frontend
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-18.04
    environment:
      name: dev
    env:
      FRONTEND_BUCKET: ${{ secrets.FRONTEND_BUCKET }}
      BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # Install and Build
      - name: Build
        run: |
          yarn install --production=false
          yarn build

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # AWS Credentials
      - name: Upload files
        run: |
          aws s3 cp dist s3://$FRONTEND_BUCKET --recursive --region $AWS_DEFAULT_REGION
