name: PUSH_T) Terraform Apply

on:
  push:
    paths:
      - terraform/**
      - .github/workflows/push_terraform.yml
    branches-ignore:
      - releases/**
  workflow_run:
    workflows:
      - PUSH_B) Backend Build
    branches:
      - master
    types:
      - completed

env:
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: terraform
  Environment: dev

jobs:
  Terraform:
    uses: ./.github/workflows/reusable_terraform.yml
    with:
      environment: dev
      region: us-east-1
      working-directory: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
