name: PUSH_F) React Build

on:
  push:
    paths:
      - frontend/**
      - .github/workflows/push_frontend.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: frontend
  NODE_ENV: production
  SSM_PARAMETER_NAME: /arms/frontend

jobs:
  build:
    runs-on: ubuntu-18.04
    environment:
      name: dev
    env:
      BUCKET_NAME_FRONTEND: ${{ secrets.BUCKET_NAME_FRONTEND }}
      BUCKET_NAME_ARCHIVE: ${{ secrets.BUCKET_NAME_ARCHIVE }}
      BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # Install and Build
      - name: Build
        run: |
          yarn install --production=false
          yarn build

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Upload dist files
      - name: Upload files
        env:
          FILE_NAME: ${{ github.sha }}
        run: |
          cd dist && zip -r -q $FILE_NAME.zip *
          aws s3 cp $FILE_NAME.zip s3://$BUCKET_NAME_ARCHIVE/frontend/$FILE_NAME.zip --region $AWS_DEFAULT_REGION
          aws ssm put-parameter --name $SSM_PARAMETER_NAME --type "String" --value s3://$BUCKET_NAME_ARCHIVE/frontend/$FILE_NAME.zip --overwrite

      # Deploy frontend
      - name: Deploy
        env:
          FILE_NAME: ${{ github.sha }}
        run: |
          filepath=$(aws ssm get-parameter --name $SSM_PARAMETER_NAME --with-decryption | jq -r .Parameter.Value)
          aws s3 cp $filepath dist.zip
          unzip -o dist.zip -d ./dist/
          aws s3 cp dist s3://$BUCKET_NAME_ARCHIVE/dist --recursive --region $AWS_DEFAULT_REGION
