name: PUSH_T) Setup Build

on:
  push:
    paths:
      - terraform/setup/**
      - .github/workflows/push_terraform_setup.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  TF_VAR_region: us-east-1
  WORKING_DIR: terraform/setup

jobs:
  Update:
    runs-on: ubuntu-18.04
    environment:
      name: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI 
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Terraform Apply
      - name: Terraform init
        run: |
          terraform init

      - name: Terraform plan
        run: |
          terraform plan -out=setup

      - name: Terraform Apply
        run: |
          terraform apply "setup"