name: RELEASE_B) Authorizer Build

on:
  workflow_run:
    workflows:
      - RELEASE_T) Backend Build
    types:
      - completed

env:
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: backend/src/authorizer

jobs:
  build:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: prod
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # Install and Build
      - name: Build
        id: build
        run: |
          yarn install
          yarn build
