name: RELEASE_T) Setup Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  TF_VAR_region: ap-northeast-1
  WORKING_DIR: terraform/setup

jobs:
  Update:
    runs-on: ubuntu-18.04
    environment:
      name: prod
    env:
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI 
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # Terraform Apply
      - name: Terraform Apply
        run: |
          mv main.tf.prod main.tf
          cat main.tf
          echo $AWS_ACCESS_KEY_ID
          terraform init
          terraform plan -out=setup
          terraform apply "setup"
