name: RELEASE_T) Service Build

on:
  workflow_run:
    workflows:
      - RELEASE_T) Setup Build
    types:
      - completed
  workflow_dispatch:

env:
  TF_VAR_admin_email: ${{ secrets.ADMIN_EMAIL }} 
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIR: terraform/services

jobs:
  Update:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: prod
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Install the latest version of Terraform CLI 
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      # Terraform Apply
      - name: Terraform Apply
        run: |
          mv main.tf.prod main.tf
          terraform init
          terraform plan -out=services
          terraform apply "services"
