name: RELEASE

on:
  release:
    types:
      - prereleased
      - edited
      - published

env:
  ENVIRONMENT: prod
  TABLE_NAME_EVENT_TYPE: spotlight-eventtype-prod
  TABLE_NAME_RESOURCES: spotlight-resources-prod
  TABLE_NAME_SETTINGS: spotlight-settings-prod

jobs:
  Terraform:
    uses: ./.github/workflows/reusable_terraform.yml
    with:
      environment: prod
      region: us-east-1
      working-directory: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Lambda_Daily_Batch:
    uses: ./.github/workflows/reusable_lambda_code.yml
    needs: Terraform
    concurrency: dailybatch
    with:
      region: us-east-1
      working-directory: backend/daily_batch
      function-name: spotlight-dailybatch-prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Lambda_CloudTrail:
    uses: ./.github/workflows/reusable_lambda_container.yml
    needs: Terraform
    concurrency: cloudtrail
    with:
      region: us-east-1
      working-directory: backend/cloudtrail
      function-name: spotlight-cloudtrail-process-prod
      dockerfile: Dockerfile.CloudTrail
      repository: spotlight/cloudtrail-prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Lambda_Report:
    uses: ./.github/workflows/reusable_lambda_container.yml
    needs: Terraform
    concurrency: report
    with:
      region: us-east-1
      working-directory: backend/cloudtrail
      function-name: spotlight-report-prod
      dockerfile: Dockerfile.Report
      repository: spotlight/report-prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Patch:
    needs: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/cloudtrail

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install and Patch
      - name: Patch
        run: |
          npm install -g ts-node typescript tsconfig-paths
          yarn install
          ts-node -r tsconfig-paths/register test/initialize/index.ts
          ts-node -r tsconfig-paths/register test/patch.ts
