name: RELEASE

on:
  release:
    types:
      - prereleased
      - edited
      - published

env:
  ENVIRONMENT: prod

jobs:
  Terraform:
    uses: ./.github/workflows/reusable_terraform.yml
    with:
      environment: prod
      region: us-east-1
      working-directory: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Lambda_Daily_Batch:
    uses: ./.github/workflows/reusable_lambda_code.yml
    needs: Terraform
    concurrency: dailybatch
    with:
      region: us-east-1
      working-directory: backend/daily_batch
      function-name: spotlight-dailybatch-prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Lambda_CloudTrail:
    uses: ./.github/workflows/reusable_lambda_container.yml
    needs: Terraform
    concurrency: cloudtrail
    with:
      region: us-east-1
      working-directory: backend/cloudtrail
      function-name: spotlight-cloudtrail-process-prod
      dockerfile: Dockerfile.CloudTrail
      repository: spotlight/cloudtrail-prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Patch:
    needs: Terraform
    runs-on: ubuntu-latest
    env:
      TABLE_NAME_UNPROCESSED: spotlight-unprocessed
    defaults:
      run:
        working-directory: backend/cloudtrail

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install and Patch
      - name: Patch
        run: |
          export TABLE_NAME_UNPROCESSED=$TABLE_NAME_UNPROCESSED-$ENVIRONMENT
          yarn install
          ts-node -r tsconfig-paths/register test/patch.ts
